### ISSUE TITLE
Publish UMM-T Record for SWODLR

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#45]

**Comment by frankinspace** [comment]
Automated publish failed https://github.com/podaac/swodlr-ui/actions/runs/6831074048/job/18580035458

```
Run podaac/cmr-umm-updater@0.5.0
  with:
    umm-json: cmr/uat_swodlr_cmr_umm_t.json
    provider: POCLOUD
    env: uat
    version: v1.0.0-rc.2
    timeout: 60
    disable_removal: true
    umm_type: umm-t
    use_associations: false
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: podaac/swodlr-ui
    TERRAFORM_VERSION: 1.3.10
    THE_ENV: uat
    TARGET_ENV_UPPERCASE: UAT
    THE_VERSION: v1.0.0-rc.2
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    SWODLR_UI_BUCKET: podaac-svc-uat-swodlr-ui
    LAUNCHPAD_TOKEN_SIT: ***
    LAUNCHPAD_TOKEN_UAT: ***
    LAUNCHPAD_TOKEN_OPS: ***
/usr/bin/docker run --name f126e800ce9d4c5eba9bb99d040ac344_e0e1c5 --label 081371 --workdir /github/workspace --rm -e "REGISTRY" -e "IMAGE_NAME" -e "TERRAFORM_VERSION" -e "THE_ENV" -e "TARGET_ENV_UPPERCASE" -e "THE_VERSION" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "SWODLR_UI_BUCKET" -e "LAUNCHPAD_TOKEN_SIT" -e "LAUNCHPAD_TOKEN_UAT" -e "LAUNCHPAD_TOKEN_OPS" -e "INPUT_UMM-JSON" -e "INPUT_PROVIDER" -e "INPUT_ENV" -e "INPUT_VERSION" -e "INPUT_TIMEOUT" -e "INPUT_DISABLE_REMOVAL" -e "INPUT_UMM_TYPE" -e "INPUT_USE_ASSOCIATIONS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/swodlr-ui/swodlr-ui":"/github/workspace" 081371:f126e800ce9d4c5eba9bb99d040ac344  "cmr/uat_swodlr_cmr_umm_t.json" "POCLOUD" "uat" "v1.0.0-rc.2" "60" "true" "umm-t" "false"
INFO:root:Starting UMM-T update
INFO:root:native_id: POCLOUD_swodlr
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 0.5s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 0.8s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 1.3s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 2.8s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 3.8s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 4.6s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 12.5s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 2.5s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
INFO:backoff:Backing off pull_concept_id(...) for 10.0s (None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "GET /search/tools.json?provider=POCLOUD&native_id=POCLOUD_swodlr HTTP/1.1" 200 None
ERROR:backoff:Giving up pull_concept_id(...) after 10 tries (None)
INFO:root:No CMR profile found. Creating new UMM-T record...
DEBUG:podaac.ummt_updater.util.tool_update:Environment url-prefix used to create_tool: https://cmr.uat.earthdata.nasa.gov/
DEBUG:podaac.ummt_updater.util.tool_update:URL used to create_tool: https://cmr.uat.earthdata.nasa.gov/ingest/providers/POCLOUD/tools/POCLOUD_swodlr
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cmr.uat.earthdata.nasa.gov:443
DEBUG:urllib3.connectionpool:[https://cmr.uat.earthdata.nasa.gov:443](https://cmr.uat.earthdata.nasa.gov/) "PUT /ingest/providers/POCLOUD/tools/POCLOUD_swodlr HTTP/1.1" 400 None
INFO:podaac.ummt_updater.util.tool_update:Response from create_tool: {"errors":["#: extraneous key [PotentialAction] is not permitted","#/MetadataSpecification/Version: 1.1.1 is not a valid enum value","#/MetadataSpecification/URL: https://cdn.earthdata.nasa.gov/umm/tool/v1.1.1 is not a valid enum value"]}
ERROR:podaac.ummt_updater.util.tool_update:Error creating tool
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/podaac/ummt_updater/util/tool_update.py", line 97, in create_tool
    req.raise_for_status()
  File "/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cmr.uat.earthdata.nasa.gov/ingest/providers/POCLOUD/tools/POCLOUD_swodlr
400 Client Error: Bad Request for url: https://cmr.uat.earthdata.nasa.gov/ingest/providers/POCLOUD/tools/POCLOUD_swodlr
```
